import type { CreatorProfile, BuilderProfile, UserProgress, GrowthScore, ScheduledPost } from '../types';
export function buildExportBundle(creator: CreatorProfile, me: BuilderProfile, progress: UserProgress, score: GrowthScore, schedule: ScheduledPost[]) {
  const playbookMd = [`# ${creator.name} Growth Playbook`, '', `Source: ${'https://creatorplaybooks.netlify.app'}/api/creator?id=${creator.id}`, '', ...creator.plays.map((p) => [`## ${p.emoji} ${p.title}`, p.description, '', `**Action:** ${p.action}`, `**Frequency:** ${p.frequency}`, ''].join('\n'))].join('\n');
  return {
    'concept.json': JSON.stringify({ name: me.project, handle: me.handle, goal: me.goal, url: me.url, mentor: creator.id }, null, 2),
    'schedule.json': JSON.stringify(schedule, null, 2),
    'builder.json': JSON.stringify(me, null, 2),
    'progress.json': JSON.stringify({ ...progress, score }, null, 2),
    'playbook.md': playbookMd,
    'README.md': `# ${me.project} agent kit\n\nMentor playbook: ${creator.name} (${creator.handle})\nGenerated by CreatorPlaybooks\n`,
    'index.html': `<!doctype html><html><head><meta charset="utf-8"><title>${me.project}</title></head><body><pre>${playbookMd}</pre></body></html>`,
  };
}
