[greeter]
background = /usr/share/backgrounds/zothos/hermetic-matrix.png
theme-name = Zoth-Hermetic-Matrix
icon-theme-name = Zoth-Hermetic
font-name = JetBrains Mono 10
user-background = false
hide-user-image = false
default-user-image = /usr/share/icons/Zoth-Hermetic/scalable/apps/zoth-studio.svg
screensaver-timeout = 0
indicators = ~host;~spacer;~clock;~power
clock-format = %a, %d %b %H:%M
