#!/bin/bash
# =============================================================================
# AI & Coffee — Create Stripe Payment Links
# =============================================================================
# Usage:
#   ./create_payment_links.sh                    # test mode (default)
#   ./create_payment_links.sh --live             # production / live mode
#   ./create_payment_links.sh --live --no-site-update
#
# For live mode you MUST be authenticated to a live-capable Stripe account:
#   stripe login
# or use a live API key directly:
#   STRIPE_API_KEY=sk_live_xxx ./create_payment_links.sh --live
#
# If the Stripe CLI complains about a read-only config file, run with a writable HOME:
#   HOME=/tmp ./create_payment_links.sh --live
#
# You can also pass pre-existing price IDs so products are not recreated:
#   source .env.payment-links
#   ./create_payment_links.sh --live
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAYMENT_LINKS_FILE="$SCRIPT_DIR/payment-links.js"
PRICE_ENV_FILE="$SCRIPT_DIR/.env.payment-links"

MODE="test"
LIVE_FLAG=""
CONFIRM=""
WRITE_SITE_FILE="true"
STRIPE_VERSION="${STRIPE_VERSION:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --live|live)
      MODE="live"
      LIVE_FLAG="--live"
      CONFIRM="--confirm"
      ;;
    --test|test)
      MODE="test"
      LIVE_FLAG=""
      CONFIRM=""
      ;;
    --no-site-update)
      WRITE_SITE_FILE="false"
      ;;
    --stripe-version=*)
      STRIPE_VERSION="${1#*=}"
      ;;
    --stripe-version)
      shift
      STRIPE_VERSION="${1:-}"
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
  shift
done

if [[ "$MODE" == "live" ]]; then
  echo "🚨 LIVE MODE — creating PRODUCTION products, prices, and payment links"
else
  echo "🧪 TEST MODE — creating TEST products, prices, and payment links"
fi

# Base stripe command wrapper
stripe_cmd() {
  if [[ -n "$STRIPE_VERSION" ]]; then
    stripe $LIVE_FLAG $CONFIRM --stripe-version "$STRIPE_VERSION" "$@"
  else
    stripe $LIVE_FLAG $CONFIRM "$@"
  fi
}

# ── Helpers ─────────────────────────────────────────────────────────────────
get_id() {
  echo "$1" | grep -o '"id": "[^"]*"' | head -1 | cut -d'"' -f4
}

get_url() {
  echo "$1" | grep -o '"url": "[^"]*"' | head -1 | cut -d'"' -f4
}

abort_on_api_error() {
  local json="$1"
  local context="$2"

  if echo "$json" | grep -q '"error"'; then
    echo "❌ Stripe API error while $context" >&2
    echo "$json" >&2
    exit 1
  fi
}

write_price_env_file() {
  cat > "$PRICE_ENV_FILE" <<EOF
# Generated by ./create_payment_links.sh on $(date -Iseconds)
# Source this file before re-running the script if you want to re-use the same prices:
#   source .env.payment-links

WORKSHOP_PRICE_ID=$WORKSHOP_PRICE_ID
PRIVATE_PRICE_ID=$PRIVATE_PRICE_ID
PRIVATE_MONTHLY_PRICE_ID=$PRIVATE_MONTHLY_PRICE_ID
PRIVATE_ANNUAL_PRICE_ID=$PRIVATE_ANNUAL_PRICE_ID
STARTER_PRICE_ID=$STARTER_PRICE_ID
AUTOPILOT_PRICE_ID=$AUTOPILOT_PRICE_ID
SOCIAL_PRICE_ID=$SOCIAL_PRICE_ID
EOF
}

write_site_payment_links_file() {
  cat > "$PAYMENT_LINKS_FILE" <<EOF
window.PAYMENT_LINKS = {
  class99: "$WORKSHOP_URL",
  private299: "$PRIVATE_URL",
  privateMonthly499: "$PRIVATE_MONTHLY_URL",
  privateAnnual4790: "$PRIVATE_ANNUAL_URL",
  starter19: "$STARTER_URL",
  autopilot39: "$AUTOPILOT_URL",
  media79: "$SOCIAL_URL",
  default: "$WORKSHOP_URL"
};
EOF
}

create_price() {
  local unit_amount="$1"
  local product_id="$2"
  local interval="${3:-}"

  if [[ -n "$interval" ]]; then
    local price_json
    price_json=$(stripe_cmd prices create \
      --unit-amount="$unit_amount" \
      --currency=usd \
      --product="$product_id" \
      --recurring.interval="$interval")
    abort_on_api_error "$price_json" "creating recurring price for product $product_id"
    echo "$price_json"
  else
    local price_json
    price_json=$(stripe_cmd prices create \
      --unit-amount="$unit_amount" \
      --currency=usd \
      --product="$product_id")
    abort_on_api_error "$price_json" "creating one-time price for product $product_id"
    echo "$price_json"
  fi
}

create_product_and_price() {
  local key="$1"
  local name="$2"
  local desc="$3"
  local amount="$4"
  local interval="${5:-}"

  local existing_var="${key^^}_PRICE_ID"
  if [[ -n "${!existing_var:-}" ]]; then
    echo "  → Using existing $key price ID: ${!existing_var}" >&2
    echo "${!existing_var}"
    return
  fi

  echo "  → Creating product: $name" >&2
  local prod_json
  prod_json=$(stripe_cmd products create --name="$name" --description="$desc")
  abort_on_api_error "$prod_json" "creating product $name"
  local prod_id
  prod_id=$(get_id "$prod_json")
  if [[ -z "$prod_id" ]]; then
    echo "❌ Failed to parse product ID for $name" >&2
    echo "$prod_json" >&2
    exit 1
  fi

  local dollars
  dollars=$(awk "BEGIN {printf \"%.2f\", $amount/100}")
  echo "  → Creating price for $name (\$$dollars)" >&2
  local price_json
  price_json=$(create_price "$amount" "$prod_id" "$interval")
  local price_id
  price_id=$(get_id "$price_json")
  if [[ -z "$price_id" ]]; then
    echo "❌ Failed to parse price ID for $name" >&2
    echo "$price_json" >&2
    exit 1
  fi
  echo "$price_id"
}

# ── Preflight auth check ────────────────────────────────────────────────────
echo ""
echo "=== Preflight auth check ==="
if ! stripe_cmd prices list --limit=1 >/dev/null 2>&1; then
  echo "❌ Stripe CLI auth failed in $MODE mode."
  if [[ "$MODE" == "live" ]]; then
    echo "   Run: stripe login"
    echo "   Or run interactively with a live key: HOME=/tmp stripe login --interactive"
  else
    echo "   Run: stripe login"
  fi
  echo "   Or provide an API key: STRIPE_API_KEY=sk_xxx ./create_payment_links.sh $MODE"
  echo "   If you see a 'read-only file system' error, use: HOME=/tmp ./create_payment_links.sh $MODE"
  exit 1
fi
echo "✅ Stripe CLI authenticated"
if [[ -n "$STRIPE_VERSION" ]]; then
  echo "✅ Stripe API version override: $STRIPE_VERSION"
fi

# ── Resolve or create Price IDs ─────────────────────────────────────────────
echo ""
echo "=== Resolving Price IDs ==="

WORKSHOP_PRICE_ID=$(create_product_and_price "workshop" \
  "AI & Coffee Workshop" \
  "The 60-minute neighborhood class that takes you from zero to your own working AI agent. Includes drink & pastry, cheatsheet, and 30-day free trial of your AI helper." \
  "9900")

PRIVATE_PRICE_ID=$(create_product_and_price "private" \
  "Private AI & Coffee Session" \
  "Dedicated private 1-on-1 setup on your schedule. Agent configured for your business + integration help." \
  "29900")

PRIVATE_MONTHLY_PRICE_ID=$(create_product_and_price "private_monthly" \
  "Private Monthly Retainer" \
  "2 private sessions per month. Ongoing support and agent improvements." \
  "49900" "month")

PRIVATE_ANNUAL_PRICE_ID=$(create_product_and_price "private_annual" \
  "Private Annual Retainer" \
  "Best value — 24 sessions per year (2 per month). Save 20%." \
  "479000" "year")

STARTER_PRICE_ID=$(create_product_and_price "starter" \
  "Starter Helper" \
  "Perfect for basic online Q&A. Keeps your custom business training active so you never miss customer question leads." \
  "1900" "month")

AUTOPILOT_PRICE_ID=$(create_product_and_price "autopilot" \
  "Autopilot Pro" \
  "Everything in Starter + booking & scheduling, pre-orders & reservations, automated text follow-ups, and daily morning lead summaries." \
  "3900" "month")

SOCIAL_PRICE_ID=$(create_product_and_price "social" \
  "Social & Media" \
  "Everything in Autopilot Pro + graphic & banner ad design, video clip & reel promos, custom AI voice generation, and premium model access." \
  "7900" "month")

# ── Create Payment Links ──────────────────────────────────────────────────────
echo ""
echo "=== Creating Payment Links ==="

WORKSHOP_LINK=$(stripe_cmd payment_links create \
  -d "line_items[0][price]=$WORKSHOP_PRICE_ID" \
  -d "line_items[0][quantity]=1")
WORKSHOP_URL=$(get_url "$WORKSHOP_LINK")
echo "class99     → $WORKSHOP_URL"

PRIVATE_LINK=$(stripe_cmd payment_links create \
  -d "line_items[0][price]=$PRIVATE_PRICE_ID" \
  -d "line_items[0][quantity]=1")
PRIVATE_URL=$(get_url "$PRIVATE_LINK")
echo "private299  → $PRIVATE_URL"

PRIVATE_MONTHLY_LINK=$(stripe_cmd payment_links create \
  -d "line_items[0][price]=$PRIVATE_MONTHLY_PRICE_ID" \
  -d "line_items[0][quantity]=1" \
  -d "subscription_data[trial_period_days]=30")
PRIVATE_MONTHLY_URL=$(get_url "$PRIVATE_MONTHLY_LINK")
echo "privateMonthly499 → $PRIVATE_MONTHLY_URL"

PRIVATE_ANNUAL_LINK=$(stripe_cmd payment_links create \
  -d "line_items[0][price]=$PRIVATE_ANNUAL_PRICE_ID" \
  -d "line_items[0][quantity]=1" \
  -d "subscription_data[trial_period_days]=30")
PRIVATE_ANNUAL_URL=$(get_url "$PRIVATE_ANNUAL_LINK")
echo "privateAnnual4790 → $PRIVATE_ANNUAL_URL"

STARTER_LINK=$(stripe_cmd payment_links create \
  -d "line_items[0][price]=$STARTER_PRICE_ID" \
  -d "line_items[0][quantity]=1" \
  -d "subscription_data[trial_period_days]=30")
STARTER_URL=$(get_url "$STARTER_LINK")
echo "starter19   → $STARTER_URL"

AUTOPILOT_LINK=$(stripe_cmd payment_links create \
  -d "line_items[0][price]=$AUTOPILOT_PRICE_ID" \
  -d "line_items[0][quantity]=1" \
  -d "subscription_data[trial_period_days]=30")
AUTOPILOT_URL=$(get_url "$AUTOPILOT_LINK")
echo "autopilot39 → $AUTOPILOT_URL"

SOCIAL_LINK=$(stripe_cmd payment_links create \
  -d "line_items[0][price]=$SOCIAL_PRICE_ID" \
  -d "line_items[0][quantity]=1" \
  -d "subscription_data[trial_period_days]=30")
SOCIAL_URL=$(get_url "$SOCIAL_LINK")
echo "media79     → $SOCIAL_URL"

write_price_env_file

if [[ "$WRITE_SITE_FILE" == "true" ]]; then
  write_site_payment_links_file
fi

# ── Output block ──────────────────────────────────────────────────────────────
echo ""
echo "✅ All Payment Links created in $MODE mode!"
echo ""
if [[ "$WRITE_SITE_FILE" == "true" ]]; then
  echo "=== Site config updated ==="
  echo "$PAYMENT_LINKS_FILE"
else
  echo "=== Site config skipped ==="
  echo "Pass without --no-site-update to overwrite $PAYMENT_LINKS_FILE"
fi

echo ""
echo "=== Price IDs written to $PRICE_ENV_FILE ==="
echo "WORKSHOP_PRICE_ID=$WORKSHOP_PRICE_ID"
echo "PRIVATE_PRICE_ID=$PRIVATE_PRICE_ID"
echo "PRIVATE_MONTHLY_PRICE_ID=$PRIVATE_MONTHLY_PRICE_ID"
echo "PRIVATE_ANNUAL_PRICE_ID=$PRIVATE_ANNUAL_PRICE_ID"
echo "STARTER_PRICE_ID=$STARTER_PRICE_ID"
echo "AUTOPILOT_PRICE_ID=$AUTOPILOT_PRICE_ID"
echo "SOCIAL_PRICE_ID=$SOCIAL_PRICE_ID"
