[Icon Theme]
Name=Zoth-Hermetic
Comment=Hermetic Emerald, Obsidian Void & Cyber Alchemical Vector Icons for ZOTHOS
Inherits=Papirus-Dark,Papirus,Adwaita,hicolor
Directories=512x512/apps,256x256/apps,128x128/apps,96x96/apps,64x64/apps,48x48/apps,32x32/apps,24x24/apps,16x16/apps,scalable/apps

[512x512/apps]
Size=512
Context=Applications
Type=Fixed

[256x256/apps]
Size=256
Context=Applications
Type=Fixed

[128x128/apps]
Size=128
Context=Applications
Type=Fixed

[96x96/apps]
Size=96
Context=Applications
Type=Fixed

[64x64/apps]
Size=64
Context=Applications
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Fixed

[24x24/apps]
Size=24
Context=Applications
Type=Fixed

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[scalable/apps]
Size=128
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable
