[Icon Theme]
Name=Zoth-Hermetic
Comment=Hermetic Emerald, Obsidian Void & Cyber Alchemical Vector Icons for ZOTHOS
Inherits=Papirus-Dark,Papirus,Adwaita,hicolor
Directories=scalable/apps,48x48/apps,128x128/apps

[scalable/apps]
Size=128
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[128x128/apps]
Size=128
Context=Applications
Type=Fixed
