plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/media/neo/f2fdda77-178b-4603-ae80-c7aa4cd97908/hermes-workspace/agent-loom/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]