export interface AgentTemplate {
  id: string;
  label: string;
  description: string;
  role: 'leaf' | 'orchestrator';
  provider: string;
  model: string;
  toolset: string[];
  skills: string[];
  instructions: string;
  loopMode: 'once' | 'loop' | 'loop-on-error' | 'loop-max';
  maxLoops: number;
  timeout: number;
  pet: string;
  color: string;
}

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'web-builder',
    label: 'Web Builder',
    description: 'Ships HTML/React artifacts, deploys to Netlify, builds UIs.',
    role: 'leaf',
    provider: 'openrouter',
    model: 'anthropic/claude-sonnet-4',
    toolset: ['browser', 'terminal', 'file', 'web'],
    skills: ['frontend-design', 'web-artifacts-builder'],
    instructions: 'You are a frontend engineer. Build production-ready HTML/React components, deploy to Netlify, and verify in browser.',
    loopMode: 'once',
    maxLoops: 3,
    timeout: 120,
    pet: 'fox',
    color: '#ff6a00',
  },
  {
    id: 'code-reviewer',
    label: 'Code Reviewer',
    description: 'Reviews PRs, scans for bugs, suggests refactors.',
    role: 'leaf',
    provider: 'openrouter',
    model: 'openai/gpt-4o',
    toolset: ['file', 'code_exec', 'delegate'],
    skills: ['testing', 'git-workflow'],
    instructions: 'You are a senior code reviewer. Read diffs, identify bugs, security issues, and style violations. Be concise and actionable.',
    loopMode: 'once',
    maxLoops: 3,
    timeout: 60,
    pet: 'owl',
    color: '#3b82f6',
  },
  {
    id: 'devops-engineer',
    label: 'DevOps Engineer',
    description: 'Provisions infra, manages CI/CD, handles Docker/K8s.',
    role: 'leaf',
    provider: 'openai',
    model: 'gpt-4.1',
    toolset: ['terminal', 'file', 'code_exec'],
    skills: ['devops'],
    instructions: 'You are a DevOps engineer. Write shell scripts, Dockerfiles, GitHub Actions workflows, and infrastructure configs.',
    loopMode: 'loop-on-error',
    maxLoops: 3,
    timeout: 120,
    pet: 'bear',
    color: '#22c55e',
  },
  {
    id: 'security-analyst',
    label: 'Security Analyst',
    description: 'Threat models, audits code, finds vulns.',
    role: 'leaf',
    provider: 'openrouter',
    model: 'anthropic/claude-opus-4',
    toolset: ['search', 'web', 'file', 'code_exec'],
    skills: ['security'],
    instructions: 'You are a security analyst. Perform threat modeling, scan for OWASP issues, and write hardened configurations.',
    loopMode: 'once',
    maxLoops: 3,
    timeout: 90,
    pet: 'raven',
    color: '#8b5cf6',
  },
  {
    id: 'data-scientist',
    label: 'Data Scientist',
    description: 'Explores data, builds notebooks, trains models.',
    role: 'leaf',
    provider: 'openrouter',
    model: 'openai/gpt-4o',
    toolset: ['code_exec', 'file', 'terminal'],
    skills: ['data-science', 'mlops'],
    instructions: 'You are a data scientist. Analyze datasets, build visualizations, and train ML models with proper evaluation.',
    loopMode: 'once',
    maxLoops: 3,
    timeout: 180,
    pet: 'cat',
    color: '#f59e0b',
  },
  {
    id: 'mlops-engineer',
    label: 'MLOps Engineer',
    description: 'Deploys models, builds pipelines, monitors training.',
    role: 'leaf',
    provider: 'openrouter',
    model: 'meta-llama/llama-3.3-70b',
    toolset: ['terminal', 'file', 'code_exec'],
    skills: ['mlops', 'devops'],
    instructions: 'You are an MLOps engineer. Set up training pipelines, model registries, and inference endpoints.',
    loopMode: 'loop-on-error',
    maxLoops: 5,
    timeout: 180,
    pet: 'wolf',
    color: '#06b6d4',
  },
  {
    id: 'research-agent',
    label: 'Research Agent',
    description: 'Deep research, literature review, synthesis.',
    role: 'leaf',
    provider: 'openrouter',
    model: 'deepseek/deepseek-r1',
    toolset: ['search', 'web', 'browser'],
    skills: ['research'],
    instructions: 'You are a research agent. Search the web, read papers, and synthesize findings into structured reports.',
    loopMode: 'loop',
    maxLoops: 5,
    timeout: 120,
    pet: 'owl',
    color: '#ec4899',
  },
  {
    id: 'doc-writer',
    label: 'Doc Writer',
    description: 'Writes READMEs, API docs, design specs.',
    role: 'leaf',
    provider: 'openai',
    model: 'gpt-4o-mini',
    toolset: ['file', 'web'],
    skills: ['documentation'],
    instructions: 'You are a technical writer. Produce clear READMEs, API documentation, and design specs.',
    loopMode: 'once',
    maxLoops: 3,
    timeout: 60,
    pet: 'lion',
    color: '#f97316',
  },
  {
    id: 'orchestrator',
    label: 'Orchestrator',
    description: 'Coordinates other agents, delegates tasks, manages workflow.',
    role: 'orchestrator',
    provider: 'openrouter',
    model: 'anthropic/claude-opus-4',
    toolset: ['delegate', 'terminal', 'file', 'web', 'search', 'browser', 'code_exec'],
    skills: ['frontend-design', 'devops', 'security', 'testing', 'git-workflow', 'research', 'documentation'],
    instructions: 'You are the orchestrator. Break down complex tasks, delegate to specialist agents, and synthesize results.',
    loopMode: 'loop-max',
    maxLoops: 5,
    timeout: 300,
    pet: 'dragon',
    color: '#a855f7',
  },
];

export const PET_EMOJI: Record<string, string> = {
  fox: '🦊',
  owl: '🦉',
  wolf: '🐺',
  raven: '🐦‍⬛',
  bear: '🐻',
  cat: '🐆',
  dog: '🐕',
  dragon: '🐲',
  tiger: '🐯',
  lion: '🦁',
};
