[Seat:*]
autologin-user=neo
autologin-user-timeout=0
autologin-session=plasma
user-session=plasma
pam-service=lightdm
pam-autologin-service=lightdm-autologin
greeter-session=lightdm-gtk-greeter
greeter-hide-users=false
greeter-show-manual-login=true
greeter-show-keyboard=yms
greeter-lock-screen=0
greeter-theme=Zoth-Hermetic-Matrix
greeter-background=/usr/share/backgrounds/zothos/hermetic-matrix.png
greeter-icon-theme=Zoth-Hermetic
greeter-setup-timeout-secs=60
